### ISSUE TITLE
Server doesn't start up

### ISSUE THREAD

**Issue by makew0rld** [linuxserver/docker-minetest#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
The logs of the container should show the server starting up

## Current Behavior
Running `docker logs minetest` shows this output repeatedly, for thousands of lines:
```
Allowed options:
  --color <value>             Coloured logs ('always', 'never' or 'auto'), defaults to 'auto'
  --config <value>            Load configuration from specified file
  --gameid <value>            Set gameid ("--gameid list" prints available ones)
  --help                      Show allowed options
  --info                      Print more information to console
  --logfile <value>           Set logfile path ('' = no logging)
  --map-dir <value>           Same as --world (deprecated)
  --migrate <value>           Migrate from current map backend to another (Only works when using minetestserver or with --server)
  --migrate-auth <value>      Migrate from current auth backend to another (Only works when using minetestserver or with --server)
  --migrate-players <value>   Migrate from current players backend to another (Only works when using minetestserver or with --server)
  --port <value>              Set network port (UDP)
  --quiet                     Print to console errors only
  --run-unittests             Run the unit tests and exit
  --terminal                  Feature an interactive terminal (Only works when using minetestserver or with --server)
  --trace                     Print enormous amounts of information to log and console
  --verbose                   Print even more information to console
  --version                   Show version information
  --world <value>             Set world path (implies local game if used with option --go)
  --worldlist <value>         Get list of worlds ('path' lists paths, 'name' lists names, 'both' lists both)
  --worldname <value>         Set world by name (implies local game if used with option --go)
```
This appears to be some issue with the minetest command line options, but when I run the command in the container manually (without the supervisor part), the server starts. My CLI args line reads: `- CLI_ARGS="--gameid minetest"`.

## Steps to Reproduce

1. Install the latest image.
2. Try and run the server.
3. Check the logs.

## Environment
**OS:** Debian Linux
**CPU architecture:** x86_64    
**How docker service was installed:** The image was installed `docker pull`, docker itself was installed through docker's apt repos.

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`
docker-compose.yml:
```yml
version: "3"

services:
  minetest:
    container_name: minetest
    image: linuxserver/minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - CLI_ARGS="--gameid minetest"
    volumes:
      - ./data/:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
```

## Docker logs

Described above.

**Comment by kuba-orlik** [comment]
I'm also experiencing this issue, is there a known workaround?

**Comment by makew0rld** [comment]
To be honest, I just ended up following [these instructions](https://wiki.minetest.net/Help:Setting_up_a_server/Debian), and installing `minetest-server` from the `buster-backports` repository.

**Comment by kuba-orlik** [comment]
I've managed to run it by changing the entrypoint so it skips the init script:

```
version: "2"
services:
  minetest:
    image: linuxserver/minetest:amd64-5.1.1-ls40
    container_name: minetest
    environment:
      - PUID=1007
      - PGID=1007
      - TZ=Europe/Warsaw
      # - CLI_ARGS="" #optional
    volumes:
      - ./data:/config/.minetest
    ports:
      - 0.0.0.0:30000:30000/udp
    entrypoint: ["/usr/bin/minetestserver", "--config", "/config/.minetest/main-config/minetest.conf"]
    restart: unless-stopped
```
