### ISSUE TITLE
Cant change Port - always defaults to 30.000

### ISSUE THREAD

**Issue by KingBBQ** [linuxserver/docker-minetest#43]
## Expected Behavior
- Setting Port to different than 30.000
- CLI: "--port 30001"
- main-config.mt: port = 30001

## Current Behavior

Server always starts up under 30000

## Steps to Reproduce

1. add port to docker-compose.yaml under "CLI port=30001"
2. docker-compose up

Result: 
2022-04-28 12:15:12: ACTION[Main]: Server for gameid="xxxx" listening on 0.0.0.0:30000.

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64

## Command used to create docker container (run/create/compose/screenshot)
```

---
version: "2.1"
services:
  minetest-augsburg-demo:
    image: ghcr.io/linuxserver/minetest
    container_name: minetest-augsburg-demo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # - CLI_ARGS=" --worldname ConnectionLost"
      - CLI_ARGS=" --world worlds --worldname NewAuxburg --port 30001"
      #- CLI_ARGS=" --worldname winter --world worlds"
      # - CLI_ARGS=" --worldname Montagsbauer --world worlds"
    volumes:
      - /opt/minetest/Augsburg2099-Demo/:/config/.minetest
    ports:
      - 30001:30001/udp
    restart: unless-stopped

```

## Docker logs
```


minetest-augsburg-demo    | 2022-04-28 12:15:12: ACTION[Server]: Announcing start to servers.minetest.net
minetest-augsburg-demo    |         .__               __                   __
minetest-augsburg-demo    |   _____ |__| ____   _____/  |_  ____   _______/  |_
minetest-augsburg-demo    |  /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
minetest-augsburg-demo    | |  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |
minetest-augsburg-demo    | |__|_|  /__|___|  /\___  >__|  \___  >____  > |__|
minetest-augsburg-demo    |       \/        \/     \/          \/     \/
minetest-augsburg-demo    | 2022-04-28 12:15:12: ACTION[Main]: World at [/config/.minetest/worlds/NewAuxburg]
minetest-augsburg-demo    | 2022-04-28 12:15:12: ACTION[Main]: Server for gameid="antigrief" listening on 0.0.0.0:30000.
```
